# general settings
name: ESRGANx3v4
model_type: ESRGANModel
scale: 3
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: HW4
    type: PairedImageDataset
    dataroot_gt: datasets/training_hr_images
    dataroot_lq: datasets/training_lr_images

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 96
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: HW4_val
    type: PairedImageDataset
    dataroot_gt: datasets/training_hr_images
    dataroot_lq: datasets/training_lr_images
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23

  
network_d:
  type: VGGStyleDiscriminator96
  num_in_ch: 3
  num_feat: 64

# path
path:
  pretrain_network_g: 
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: 0.0001
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: 0.0005
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 0.01
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight:  0.005

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: 10000
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq:  10000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
